# Generated by Django 4.1.7 on 2023-04-01 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0004_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={"verbose_name": "redactor", "verbose_name_plural": "redactors"},
        ),
    ]
